script: rake ci
language: ruby
rvm:
  - 2.2.0
  - jruby
  - ruby-head
  - jruby-head
  - rbx-2

matrix:
  allow_failures:
    - rvm: rbx-2
    - rvm: ruby-head
    - rvm: jruby-head
    - env: CELLULOID_TASK_CLASS=Threaded
    # - env: CELLULOID_TASK_CLASS=Threaded CELLULOID_GROUP_CLASS=Pool
    - env: CELLULOID_LEAKTEST=1
env:
  global:
    - NUMBER_OF_PROCESSORS=2 CELLULOID_CONFIG_FILE=.env-ci
  matrix:
    - CELLULOID_TASK_CLASS=Fibered
    - CELLULOID_TASK_CLASS=Threaded
    # - CELLULOID_TASK_CLASS=Threaded CELLULOID_GROUP_CLASS=Pool
    - CELLULOID_LEAKTEST=1
notifications:
  irc: "irc.freenode.org#celluloid"

sudo: false
install: bundle install --retry=3 --without=development
